CREATE SEQUENCE SEQ_CLIENTES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CLIENTES_DADOS (
    ID_CLIENTE INTEGER DEFAULT SEQ_CLIENTES.NEXTVAL NOT NULL,
    NOME       VARCHAR2(100) NOT NULL,
    CPF      VARCHAR2(11) UNIQUE NOT NULL,
    EMAIL      VARCHAR(20) UNIQUE NOT NULL,
    MARGEM DECIMAL DEFAULT ,
    TELEFONE VARCHAR(20) NOT NULL ,
    IDADE INTEGER DEFAULT NOT NULL ,
    OBITO VARCHAR(4) NOT NULL ,
);