CREATE SEQUENCE SEQ_COLABORADOR
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CLIENTES_DADOS
(
    ID_COLABORADOR INTEGER DEFAULT SEQ_COLABORADOR.NEXTVAL NOT NULL,
    NOME       VARCHAR2(100) NOT NULL,
    EMAIL      VARCHAR2(100) UNIQUE NOT NULL,
    CPF     VARCHAR(25) NOT NULL ,
    SENHA      VARCHAR(20) NOT NULL,
);