CREATE SEQUENCE SEQ_PROP_VENDA
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE TABLE TBL_PROPOSTA_VENDA (
    ID_PROPOSTA INTEGER DEFAULT SEQ_PROP_VENDA.NEXTVAL NOT NULL,
    BANCO VARCHAR(50) NOT NULL ,
    PARCELA_UTILIZADA DECIMAL NOT NULL ,
    PRAZO INTEGER NOT NULL ,
    VALOR_LIBERADO DECIMAL NOT NULL ,
    VALOR_LIMITE DECIMAL NOT NULL,
    ID_COLABORADOR INTEGER NOT NULL ,
    CONSTRAINT FK_ID_COLABORADOR FOREIGN KEY (ID_COLABORADOR) REFERENCES TBL_COLABORADOR(ID_COLABORADOR),
    ID_CLIENTE INTEGER NOT NULL ,
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTES_DADOS (ID_COLABORADOR)
);