CREATE SEQUENCE SEQ_VENDA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_VENDA (
    ID_VENDA INTEGER DEFAULT SEQ_VENDA.NEXTVAL NOT NULL,
    ID_COLABORADOR INTEGER NOT NULL,
    CONSTRAINT FK_ID_COLABORADOR FOREIGN KEY (ID_COLABORADOR) REFERENCES TBL_COLABORADOR (ID_COLABORADOR),
    ID_CLIENTE INTEGER NOT NULL,
    CONSTRAINT FK_ID_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTES_DADOS (ID_CLIENTE),
    VALOR_VENDA DECIMAL NOT NULL,
    COMISSAO DECIMAL NOT NULL,
);